### ISSUE TITLE
Allow users to apply to jobs

### ISSUE THREAD

**Issue by AndreiUngur** [scrum-gang/jobapplications#1]
## EPIC: Allow users to apply to jobs

This epic is meant to track all progress towards the user stories related to job applications.

### Step 1: Preparatory work

- [x] Define job postings database schema (on paper)
- [x] Reproduce database tables in Python using SQLAlchemy with PostgreSQL
- [x] Set up database migrations using Alembic
- [x] Define a REST API with a simple status end-point

### ~Step 2: Recruiters shall be able to create, view, update and delete job postings~
Update: A different team is working on this I think...
~- [ ] Add REST API end-point for each CRUD operation related to job postings~
~- [ ] Implement interaction with DB~
~- [ ] Add testing to ensure only logged in recruiters can perform the CUD operations.~
~- [ ] Add testing to ensure all users can view job postings~
~- [ ] Add testing to ensure each individual CUD operation is functional~

### Step 3: Applicants shall be able to apply for job postings

- [x] Add REST API end-points for the application process
- [x] Implement interaction with DB and server-side storage system (for resumes)
- [x] Add testing to ensure recruiters can view all applications
- [x] Add testing to ensure  users can view their personal applications
- [x] Add testing to ensure the data stored during a job application is accurate

### Step 4: Applicants shall be able to track job postings

- [x] Add REST API end-points for the tracking process
- [x] Implement interaction with DB
- [x] Add testing to ensure applicants can correctly track job postings

### Step 5: Applicants shall be able to add external job postings

- [x] Create REST API end-point which takes as input an external job posting's URL
- [x] Add business logic to parse external job posting web page and return relevant information alongside the original link
- [x] Add testing to ensure external API calls are made correctly
- [x] Add testing to ensure web page text is parsed reasonably well

**Comment by AndreiUngur** [comment]
API is basically done, we just need to add authentication !
