### ISSUE TITLE
Create REST API end-points & DB interaction for the tracking process of external postings

### ISSUE THREAD

**Issue by andibakti** [scrum-gang/jobapplications#10]
Related to step 5 (see Epic #1 )
## Features
- [x] Add REST API end-point for tracking external postings
- [x] Add business logic to parse external job posting web pages
- [x] Add DB interaction

## Testing
- [x] Add testing to ensure external API calls are made correctly
- [ ] Add testing to ensure web page text is parsed reasonably well
- [x] Add testing to ensure external postings are tracked correctly
