### ISSUE TITLE
Add REST API end-points & DB interaction for the tracking process of in-house postings

### ISSUE THREAD

**Issue by andibakti** [scrum-gang/jobapplications#12]
Related to step 3 (Epic #1) 

## Functionalities
- [x] Create API end-point
- [x] Handle DB interaction

## Testing
- [x] Add testing to ensure data can be successfully loaded and saved to storage system
- [x] Add testing to ensure recruiters can view all applications
- [x] Add testing to ensure users can view their personal applications
- [x] Add testing to ensure the data stored during a job application is accurate
