### ISSUE TITLE
Add REST API end-points for the tracking process

### ISSUE THREAD

**Issue by andibakti** [scrum-gang/jobapplications#8]
Related to step 4 -  Applicants shall be able to track job postings (see in Epic #1) 

## Functional
- [ ] Define REST API Endpoint
- [ ] Define DB interaction

## Testing
- [ ]  Add testing to ensure applicants can correctly track job in-house postings

**Comment by AndreiUngur** [comment]
Superceded by #10  and #12
